name: 기능 요청
description: 구현해야 할 기능을 설명해주세요.
assignees: ""
labels: feat
body:
  - type: textarea
    id: feat-description
    attributes:
      label: 기능 설명
      description: 어떤 기능인지 1-2줄 내로 간략하게 설명해주세요.
      placeholder: 기능 설명
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: 요구사항
      description: 기능이 정상적으로 동작했을 때 예상되는 결과를 적어주세요.
      placeholder: 요구사항
    validations:
      required: true
